name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        #install python
        #list all files
        #create a new file
        #list all files
    - uses: actions/checkout@v3

    - name: List all original files
      run: ls 
    
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Run Python Script
        #lets call create-file-2 to fail this job and test dependent jobs
      run: python create-file-2.py 
    
    - name: List all new files
      run: ls 
    
    - name: List all new files
      run: cat read_me.txt  

  display:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: print a value
      run: echo Just another job

  conditional:
    runs-on: ubuntu-latest
    needs: [build,display]

    steps:
    - name: print another value
      run: echo another dependent job requiring successful completion

  completion:
    runs-on: ubuntu-latest
    if: always()
    needs: [build,display]

    steps:
    - name: print yet another value
      run: echo another dependent job requiring just completion not success